### ISSUE TITLE
MDETR pretraining crashes with 8GPU on one instance, inplace modification error

### ISSUE THREAD

**Issue by nguyeho7** [ashkamath/mdetr#22]
Hello,
I tried pretraining MDETR using your guide on a 8 GPU Volta instance.
I modified the config to only contain flickr30k (removed mixed) and ran the following command:

```
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --dataset_config configs/pretrain.json --ema
```

However, it throws an error in Roberta text encoder (it's 8 times, I truncated it):

```
[W python_anomaly_mode.cpp:104] Warning: Error detected in EmbeddingBackward. Traceback of forward call that caused the error:
  File "main.py", line 648, in <module>
    main(args)
  File "main.py", line 563, in main
    model_ema=model_ema,
  File "/task_runtime/mdetr_2/mdetr/engine.py", line 68, in train_one_epoch
    memory_cache = model(samples, captions, encode_and_save=True)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/task_runtime/mdetr_2/mdetr/models/mdetr.py", line 143, in forward
    text_attention_mask=None,
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/task_runtime/mdetr_2/mdetr/models/transformer.py", line 121, in forward
    encoded_text = self.text_encoder(**tokenized)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/transformers/models/roberta/modeling_roberta.py", line 842, in forward
    past_key_values_length=past_key_values_length,
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/transformers/models/roberta/**modeling_roberta.py**", line 132, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
 (function _print_stack)


Traceback (most recent call last):
  File "main.py", line 648, in <module>
    main(args)
  File "main.py", line 563, in main
    model_ema=model_ema,
  File "/task_runtime/mdetr_2/mdetr/engine.py", line 100, in train_one_epoch
    losses.backward()
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/miniconda/envs/iris/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [2, 20]] is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!


```

**Comment by alcinos** [comment]
Hello @nguyeho7 

Thanks for your interest in MDETR.
Please try downgrading the transformers package to transformers==4.5.1 and tell me if the error persists.

Best of luck

**Comment by nguyeho7** [comment]
Thank you very much, downgrading the transformers package fixed this issue.
